package com.xiaoniu.transaction.dataObject;

public class ItemDetailDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_detail.id
     *
     * @mbg.generated Sun Mar 29 17:42:54 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_detail.item_id
     *
     * @mbg.generated Sun Mar 29 17:42:54 CST 2020
     */
    private Integer itemId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_detail.id
     *
     * @return the value of item_detail.id
     *
     * @mbg.generated Sun Mar 29 17:42:54 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_detail.id
     *
     * @param id the value for item_detail.id
     *
     * @mbg.generated Sun Mar 29 17:42:54 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_detail.item_id
     *
     * @return the value of item_detail.item_id
     *
     * @mbg.generated Sun Mar 29 17:42:54 CST 2020
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_detail.item_id
     *
     * @param itemId the value for item_detail.item_id
     *
     * @mbg.generated Sun Mar 29 17:42:54 CST 2020
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }
}