package com.xiaoniu.transaction.dao;

import com.xiaoniu.transaction.dataObject.ItemDetailDO;
import com.xiaoniu.transaction.dataObject.ItemDetailDOWithBLOBs;
import org.springframework.stereotype.Repository;

@Repository
public interface ItemDetailDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_detail
     *
     * @mbg.generated Sun Mar 29 17:42:54 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_detail
     *
     * @mbg.generated Sun Mar 29 17:42:54 CST 2020
     */
    int insert(ItemDetailDOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_detail
     *
     * @mbg.generated Sun Mar 29 17:42:54 CST 2020
     */
    int insertSelective(ItemDetailDOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_detail
     *
     * @mbg.generated Sun Mar 29 17:42:54 CST 2020
     */
    ItemDetailDOWithBLOBs selectByPrimaryKey(Integer id);

    ItemDetailDOWithBLOBs selectByItemId(Integer itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_detail
     *
     * @mbg.generated Sun Mar 29 17:42:54 CST 2020
     */
    int updateByPrimaryKeySelective(ItemDetailDOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_detail
     *
     * @mbg.generated Sun Mar 29 17:42:54 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(ItemDetailDOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_detail
     *
     * @mbg.generated Sun Mar 29 17:42:54 CST 2020
     */
    int updateByPrimaryKey(ItemDetailDO record);
}