package com.xiaoniu.transaction.dao;

import com.xiaoniu.transaction.dataObject.ItemDetailDO;
import org.springframework.stereotype.Repository;

@Repository
public interface ItemDetailDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_detail
     *
     * @mbg.generated Tue Mar 24 13:01:27 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_detail
     *
     * @mbg.generated Tue Mar 24 13:01:27 CST 2020
     */
    int insert(ItemDetailDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_detail
     *
     * @mbg.generated Tue Mar 24 13:01:27 CST 2020
     */
    int insertSelective(ItemDetailDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_detail
     *
     * @mbg.generated Tue Mar 24 13:01:27 CST 2020
     */
    ItemDetailDO selectByPrimaryKey(Integer id);

    ItemDetailDO selectByItemId(Integer itemId);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_detail
     *
     * @mbg.generated Tue Mar 24 13:01:27 CST 2020
     */
    int updateByPrimaryKeySelective(ItemDetailDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_detail
     *
     * @mbg.generated Tue Mar 24 13:01:27 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(ItemDetailDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_detail
     *
     * @mbg.generated Tue Mar 24 13:01:27 CST 2020
     */
    int updateByPrimaryKey(ItemDetailDO record);
}