package com.xiaoniu.transaction.dao;

import com.xiaoniu.transaction.dataObject.UserInfoDO;
import org.springframework.stereotype.Repository;

@Repository
public interface UserInfoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Wed Apr 01 17:27:17 CST 2020
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Wed Apr 01 17:27:17 CST 2020
     */
    int insert(UserInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Wed Apr 01 17:27:17 CST 2020
     */
    int insertSelective(UserInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Wed Apr 01 17:27:17 CST 2020
     */
    UserInfoDO selectByPrimaryKey(Integer userId);

    UserInfoDO selectByEmail(String email);

    UserInfoDO selectByUserId(Integer userId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Wed Apr 01 17:27:17 CST 2020
     */
    int updateByPrimaryKeySelective(UserInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Wed Apr 01 17:27:17 CST 2020
     */
    int updateByPrimaryKey(UserInfoDO record);
}